In [1]:
import numpy as np # linear algebra
import pandas as pd

In [2]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [3]:
df = pd.read_csv('code_main.csv')

In [4]:
df.head()

,Location,State,Location type,Popularity
0,Agumbe,"Karnataka,","birdwatching,rainforest,waterfall,",81333659
1,Almora,"Uttarakhand,","mountainviews,",19434475
2,Amarkantak,"Madhya Pradesh,","forest,religious,camping,",25554067
3,Amboli,"Maharashtra,","waterfalls,landscapes,",43569238
4,Ananthagiri Hills,"Andhra Pradesh,","trekking,caves,landscapes,",93277569

In [5]:
df['tags'] = df['State'].astype(str) + df['Location type'].astype(str) + df['Popularity'].astype(str)

In [6]:
df.head()

,Location,State,Location type,Popularity,tags
0,Agumbe,"Karnataka,","birdwatching,rainforest,waterfall,",81333659,"Karnataka,birdwatching,rainforest,waterfall,8..."
1,Almora,"Uttarakhand,","mountainviews,",19434475,"Uttarakhand,mountainviews,19434475"
2,Amarkantak,"Madhya Pradesh,","forest,religious,camping,",25554067,"Madhya Pradesh,forest,religious,camping,25554067"
3,Amboli,"Maharashtra,","waterfalls,landscapes,",43569238,"Maharashtra,waterfalls,landscapes,43569238"
4,Ananthagiri Hills,"Andhra Pradesh,","trekking,caves,landscapes,",93277569,"Andhra Pradesh,trekking,caves,landscapes,9327..."

In [7]:
new_df=df[['Location','tags']]

In [8]:
new_df

             Location                                               tags
0              Agumbe   Karnataka,birdwatching,rainforest,waterfall,8...
1              Almora                 Uttarakhand,mountainviews,19434475
2          Amarkantak   Madhya Pradesh,forest,religious,camping,25554067
3              Amboli         Maharashtra,waterfalls,landscapes,43569238
4   Ananthagiri Hills   Andhra Pradesh,trekking,caves,landscapes,9327...
5        Araku Valley     Andhra Pradesh,waterfalls,coffefields,93277569
6                Auli        Uttarakhand,trekking,hiking,skiing,19434475
7         Bir Billing  Himachal Pradesh,paragliding,camping,trekking,...
8             Bomdila  Arunachal Pradesh,monasteries,appleorchards,la...
9           Champawat          Uttarakhand,landscapes,religious,19434475
10           Champhai               Mizoram,landscapes,mizoculture,87232
11        Cherrapunji           Meghalaya,rainforest,birdwatching,154409
12        Chikmagalur   Karnataka,trekking,coffeefields,landscapes,81...
13             Chopta                Uttarakhand,camping,forest,19434475
14              Coorg   Karnataka,cycling,forest,camping,rafting,safa...
15         Daringbadi                  Odisha,coffeefield,forest,3742221
16         Darjeeling   West Bengal,trekking,hiking,mountains,gardens...
17          Dharamkot   Himachal Pradesh,trekking,yoga,landscapes,563...
18        Dharamshala   Himachal Pradesh,camping,monasteries,trekking...
19            Gangtok   Sikkim,paragliding,monasteries,trekking,cable...
20            Gulmarg  Jammu&Kashmir,skiing,cablecarride,snowpeak,113...
21      Horsley Hills   Andhra Pradesh,zipling,trekking,landscapes,93...
22        Kolli Hills   Tamil Nadu,waterfalls,trekking,forests,campin...
23          Kudremukh        Karnataka,trekking,forest,wildlife,81333659
24             Ladakh   Jammu & Kashmir,camping,motorsport,trekking,r...
25           Lonavala      Maharashtra,waterfalls,boating,caves,43569238
26             Manali  Himachal Pradesh,trekking,hiking,cycling,skiin...
27          Mount Abu   Rajasthan,Rockclimbing,trekking,camping,21988734
28             Munnar                    Kerala,trekking,hiking,81333659
29          Mussoorie           Uttarakhand,trekking,waterfalls,19434475
30           Nainital  Uttarakhand,safari,religious,boating,snowpeak,...
31               Ooty   Tamil Nadu,trekking,hiking,boating,garden,bot...
32           Pahalgam  JammuandKashmir,trekking,camping,valley,landsc...
33           Saputara   Gujarat,boating,trekking,lake,landscapes,2452...
34           Shillong   Meghalaya,waterfalls,golfcourse,landscapes,la...
35             Shimla  Himachal Pradesh,religious,camping,trekking,56...
36           Srinagar       Jammu & Kashmir,lake,garden,boating,11314920
37             Jaipur  Rajasthan,lake,garden,boating,monuments,sights...
38            Udaipur  Rajasthan,biking,museums,monuments,forts,21988734
39            Bikaner  Rajasthan,desertsafari,museums,forts,monuments...
40             Mysuru  Karnataka,sightseeing,museums,religious,safari...
41           Manglore  Karnataka,surfing,religious,beaches,parasailin...
42        Chikmagalur  Karnataka,religious,waterfalls,lakes,boating,r...
43              Sohra  Meghalaya,waterfalls,boating,caves,lakes,valle...
44            Kachchh  Gujarat,sightseeing,safari,beaches,desert,2452...
45            Somnath  Gujarat,beaches,religious,surfing,parasailing,...
46         Coimbatore  TamilNadu,Museums,safari,waterfalls,religious,...
47            Madurai  TamilNadu,safari,sightseeing,monuments,religio...
48              Kochi  Kerala,islands,religious,beaches,safari,surfin...
49         Trivandrum  Kerala,Sightseeing,beaches,safari,religious,81...
50             Nashik       Maharashtra,waterfalls,safari,tours,43569238
51            peeling  Sikkim,waterfalls,religious,mountains,trekking...
52            Lachung  Sikkim,lakes,boating,mountains,snowpeaks,skiin...
53           Siliguri  WestBengal,lakes,boating,mountains,safari,fore...
54               Puri  Odisha,beaches,religious,surfing,parasailing,l...
55           Balasore  Odisha,Religious,lakes,beaches,waterfalls,safa...

In [130]:
#new = df.drop(columns=['Popularity','Location type','State'])
#new.head()

In [131]:
#new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())
#new.df

In [9]:

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=58,stop_words='english')

In [ ]:
empty_strings = new['tags'][new['tags'].isnull()]
print(f"Number of empty strings: {len(empty_strings)}")

In [134]:
#new['tags'] = new['tags'].dropna()

In [11]:
vector = cv.fit_transform(new_df['tags']).toarray()

In [12]:
from sklearn.metrics.pairwise import cosine_similarity

In [13]:
similarity = cosine_similarity(vector)

In [14]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])

[(0, 1.0000000000000002),
 (23, 0.5773502691896258),
 (12, 0.5163977794943223),
 (14, 0.4714045207910318),
 (40, 0.4714045207910318),
 (41, 0.4714045207910318),
 (42, 0.4364357804719848),
 (11, 0.3333333333333334),
 (28, 0.2886751345948129),
 (49, 0.2357022603955159),
 (48, 0.2182178902359924),
 (1, 0.0),
 (2, 0.0),
 (3, 0.0),
 (4, 0.0),
 (5, 0.0),
 (6, 0.0),
 (7, 0.0),
 (8, 0.0),
 (9, 0.0),
 (10, 0.0),
 (13, 0.0),
 (15, 0.0),
 (16, 0.0),
 (17, 0.0),
 (18, 0.0),
 (19, 0.0),
 (20, 0.0),
 (21, 0.0),
 (22, 0.0),
 (24, 0.0),
 (25, 0.0),
 (26, 0.0),
 (27, 0.0),
 (29, 0.0),
 (30, 0.0),
 (31, 0.0),
 (32, 0.0),
 (33, 0.0),
 (34, 0.0),
 (35, 0.0),
 (36, 0.0),
 (37, 0.0),
 (38, 0.0),
 (39, 0.0),
 (43, 0.0),
 (44, 0.0),
 (45, 0.0),
 (46, 0.0),
 (47, 0.0),
 (50, 0.0),
 (51, 0.0),
 (52, 0.0),
 (53, 0.0),
 (54, 0.0),
 (55, 0.0)]

In [121]:
#new['tags'] = new['tags'].apply(lambda x: " ".join(x))
#new.head()

            Location                                               tags
0             Agumbe    K a r n a t a k a , b i r d w a t c h i n g ...
1             Almora  U t t a r a k h a n d , m o u n t a i n v i e ...
2         Amarkantak    M a d h y a   P r a d e s h , f o r e s t , ...
3             Amboli    M a h a r a s h t r a , w a t e r f a l l s ...
4  Ananthagiri Hills    A n d h r a   P r a d e s h , t r e k k i n ...

In [15]:
def recommend(place):
    places_index=new_df[new_df['Location'] == place].index[0]
    distances=similarity[places_index]
    places_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]
    m_l=[]
    for i in places_list :
        a=new_df.iloc[i[0]].Location
        m_l.append(a)
    return m_l

In [17]:
recommend('Manali')

['Dharamkot', 'Bir Billing', 'Dharamshala', 'Shimla', 'Auli']

In [74]:
#new_df=places[['Location','tags']]

In [53]:
#new_df

             Location                                               tags
0              Agumbe   Karnataka,birdwatching,rainforest,waterfall,8...
1              Almora                 Uttarakhand,mountainviews,19434475
2          Amarkantak   Madhya Pradesh,forest,religious,camping,25554067
3              Amboli         Maharashtra,waterfalls,landscapes,43569238
4   Ananthagiri Hills   Andhra Pradesh,trekking,caves,landscapes,9327...
5        Araku Valley     Andhra Pradesh,waterfalls,coffefields,93277569
6                Auli        Uttarakhand,trekking,hiking,skiing,19434475
7         Bir Billing  Himachal Pradesh,paragliding,camping,trekking,...
8             Bomdila  Arunachal Pradesh,monasteries,appleorchards,la...
9           Champawat          Uttarakhand,landscapes,religious,19434475
10           Champhai               Mizoram,landscapes,mizoculture,87232
11        Cherrapunji           Meghalaya,rainforest,birdwatching,154409
12        Chikmagalur   Karnataka,trekking,coffeefields,landscapes,81...
13             Chopta                Uttarakhand,camping,forest,19434475
14              Coorg   Karnataka,cycling,forest,camping,rafting,safa...
15         Daringbadi                  Odisha,coffeefield,forest,3742221
16         Darjeeling   West Bengal,trekking,hiking,mountains,gardens...
17          Dharamkot   Himachal Pradesh,trekking,yoga,landscapes,563...
18        Dharamshala   Himachal Pradesh,camping,monasteries,trekking...
19            Gangtok   Sikkim,paragliding,monasteries,trekking,cable...
20            Gulmarg  Jammu&Kashmir,skiing,cablecarride,snowpeak,113...
21      Horsley Hills   Andhra Pradesh,zipling,trekking,landscapes,93...
22        Kolli Hills   Tamil Nadu,waterfalls,trekking,forests,campin...
23          Kudremukh        Karnataka,trekking,forest,wildlife,81333659
24             Ladakh   Jammu & Kashmir,camping,motorsport,trekking,r...
25           Lonavala      Maharashtra,waterfalls,boating,caves,43569238
26             Manali  Himachal Pradesh,trekking,hiking,cycling,skiin...
27          Mount Abu   Rajasthan,Rockclimbing,trekking,camping,21988734
28             Munnar                    Kerala,trekking,hiking,81333659
29          Mussoorie           Uttarakhand,trekking,waterfalls,19434475
30           Nainital  Uttarakhand,safari,religious,boating,snowpeak,...
31               Ooty   Tamil Nadu,trekking,hiking,boating,garden,bot...
32           Pahalgam  JammuandKashmir,trekking,camping,valley,landsc...
33           Saputara   Gujarat,boating,trekking,lake,landscapes,2452...
34           Shillong   Meghalaya,waterfalls,golfcourse,landscapes,la...
35             Shimla  Himachal Pradesh,religious,camping,trekking,56...
36           Srinagar       Jammu & Kashmir,lake,garden,boating,11314920
37             Jaipur  Rajasthan,lake,garden,boating,monuments,sights...
38            Udaipur  Rajasthan,biking,museums,monuments,forts,21988734
39            Bikaner  Rajasthan,desertsafari,museums,forts,monuments...
40             Mysuru  Karnataka,sightseeing,museums,religious,safari...
41           Manglore  Karnataka,surfing,religious,beaches,parasailin...
42        Chikmagalur  Karnataka,religious,waterfalls,lakes,boating,r...
43              Sohra  Meghalaya,waterfalls,boating,caves,lakes,valle...
44            Kachchh  Gujarat,sightseeing,safari,beaches,desert,2452...
45            Somnath  Gujarat,beaches,religious,surfing,parasailing,...
46         Coimbatore  TamilNadu,Museums,safari,waterfalls,religious,...
47            Madurai  TamilNadu,safari,sightseeing,monuments,religio...
48              Kochi  Kerala,islands,religious,beaches,safari,surfin...
49         Trivandrum  Kerala,Sightseeing,beaches,safari,religious,81...
50             Nashik       Maharashtra,waterfalls,safari,tours,43569238
51            peeling  Sikkim,waterfalls,religious,mountains,trekking...
52            Lachung  Sikkim,lakes,boating,mountains,snowpeaks,skiin...
53           Siliguri  WestBengal,lakes,boating,mountains,safari,fore...
54               Puri  Odisha,beaches,religious,surfing,parasailing,l...
55           Balasore  Odisha,Religious,lakes,beaches,waterfalls,safa...

In [143]:
import pickle

In [144]:
pickle.dump(new_df,open('places.pkl','wb'))

In [145]:
pickle.dump(similarity,open('similarity.pkl','wb'))